// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://druwytttcxnfpwgyrvmt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRydXd5dHR0Y3huZnB3Z3lydm10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1OTQ2MjYsImV4cCI6MjA2NjE3MDYyNn0.qyAfq9sl1jimQEnKDbV90zlDloZFoHqboDHUzJeLP6I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);